In [2]:
import torch

x = torch.Tensor([5,3])
x
y = torch.Tensor([2,1])
y

print(x*y)

tensor([10.,  3.])


In [4]:
xz = torch.zeros([2,5])
print(xz)

xz.shape


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


torch.Size([2, 5])

In [6]:
yr = torch.rand([2,5])
print(yr)

tensor([[0.4009, 0.6283, 0.1031, 0.7057, 0.4147],
        [0.2405, 0.2141, 0.9904, 0.5319, 0.7578]])


In [7]:
yr.view([1,10])

tensor([[0.4009, 0.6283, 0.1031, 0.7057, 0.4147, 0.2405, 0.2141, 0.9904, 0.5319,
         0.7578]])